// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2015.04.09 18:06:07 // Generated by ComTest
 *
 */
public class HashArrayTest {



  // Generated by ComTest BEGIN
  /** testAdd22 */
  @Test
  public void testAdd22() {    // HashArray: 22
    HashArray h = new HashArray(); 
    int num; 
    boolean loytyy; 
    num = 5; 
    h.add(num); 
    loytyy = false; 
    for (int i = 0; i < h.taulu.length; i++) { if (h.taulu[i] == num) loytyy = true; }
    assertEquals("From: HashArray line: 30", true, loytyy); 
    num = 2; 
    h.add(num); 
    loytyy = false; 
    for (int i = 0; i < h.taulu.length; i++) { if (h.taulu[i] == num) loytyy = true; }
    assertEquals("From: HashArray line: 35", true, loytyy); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRemove59 */
  @Test
  public void testRemove59() {    // HashArray: 59
    HashArray h = new HashArray(); 
    h.add(5); 
    h.add(6); 
    h.remove(5); 
    assertEquals("From: HashArray line: 64", false, h.contains(5)); 
    assertEquals("From: HashArray line: 65", true, h.contains(6)); 
    h.remove(6); 
    assertEquals("From: HashArray line: 67", false, h.contains(5)); 
    assertEquals("From: HashArray line: 68", false, h.contains(6)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testContains87 */
  @Test
  public void testContains87() {    // HashArray: 87
    HashArray h = new HashArray(); 
    h.add(5); 
    h.add(6); 
    h.add(7); 
    h.add(8); 
    h.add(9); 
    h.add(10); 
    h.add(11); 
    h.add(13); 
    h.add(14); 
    h.add(15); 
    assertEquals("From: HashArray line: 99", true, h.contains(5)); 
    assertEquals("From: HashArray line: 100", true, h.contains(6)); 
    assertEquals("From: HashArray line: 101", true, h.contains(7)); 
    assertEquals("From: HashArray line: 102", true, h.contains(8)); 
    assertEquals("From: HashArray line: 103", true, h.contains(9)); 
    assertEquals("From: HashArray line: 104", true, h.contains(10)); 
    assertEquals("From: HashArray line: 105", true, h.contains(11)); 
    assertEquals("From: HashArray line: 106", true, h.contains(13)); 
    assertEquals("From: HashArray line: 107", true, h.contains(14)); 
    assertEquals("From: HashArray line: 108", true, h.contains(15)); 
    assertEquals("From: HashArray line: 109", false, h.contains(12)); 
    assertEquals("From: HashArray line: 110", false, h.contains(1)); 
    assertEquals("From: HashArray line: 111", false, h.contains(22)); 
  } // Generated by ComTest END
}