package sekalaiset;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static sekalaiset.PvmSisaltoTarkistus.*;
// Generated by ComTest END

public class PvmSisaltoTarkistusTest {

  // Generated by ComTest BEGIN
  /** testSisaltoOk25 */
  @Test
  public void testSisaltoOk25() {    // PvmSisaltoTarkistus: 25
    assertEquals("From: PvmSisaltoTarkistus line: 26", true, sisaltoOk(new int[] {5, 5, 2001})); 
    assertEquals("From: PvmSisaltoTarkistus line: 27", false, sisaltoOk(new int[] {32, 5, 2001})); 
    assertEquals("From: PvmSisaltoTarkistus line: 28", true, sisaltoOk(new int[] {12, 1, 1995})); 
    assertEquals("From: PvmSisaltoTarkistus line: 29", false, sisaltoOk(new int[] {12, 13, 1995})); 
    assertEquals("From: PvmSisaltoTarkistus line: 30", false, sisaltoOk(new int[] {12, -3, 1995})); 
    assertEquals("From: PvmSisaltoTarkistus line: 31", false, sisaltoOk(new int[] {-12, 1, 1995})); 
    assertEquals("From: PvmSisaltoTarkistus line: 32", false, sisaltoOk(new int[] {12, 1, -1995})); 
    assertEquals("From: PvmSisaltoTarkistus line: 33", false, sisaltoOk(new int[] {0, 0, 1995})); 
    assertEquals("From: PvmSisaltoTarkistus line: 34", false, sisaltoOk(new int[] {29, 2, 2001})); 
    assertEquals("From: PvmSisaltoTarkistus line: 35", true, sisaltoOk(new int[] {29, 2, 2000})); 
    assertEquals("From: PvmSisaltoTarkistus line: 36", false, sisaltoOk(new int[] {12, 1, 190})); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKarkausvuosi65 */
  @Test
  public void testKarkausvuosi65() {    // PvmSisaltoTarkistus: 65
    assertEquals("From: PvmSisaltoTarkistus line: 66", 0, karkausvuosi(1900));
    assertEquals("From: PvmSisaltoTarkistus line: 67", 0, karkausvuosi(1900));
    assertEquals("From: PvmSisaltoTarkistus line: 68", 0, karkausvuosi(1901));
    assertEquals("From: PvmSisaltoTarkistus line: 69", 1, karkausvuosi(1996));
    assertEquals("From: PvmSisaltoTarkistus line: 70", 1, karkausvuosi(2000));
    assertEquals("From: PvmSisaltoTarkistus line: 71", 0, karkausvuosi(2001));
    assertEquals("From: PvmSisaltoTarkistus line: 72", 1, karkausvuosi(2004));
  } // Generated by ComTest END
}